# general configuration
url: http://runwang.me
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/profile.jpg"
  # author will appear under the avatar (optional)
  author: "Run Wang"
  # tagline will appear under the title (optional)
  tagline: "PhD student in computer security"
  about: "Dept. of Computer School<br>Wuhan University<br><br>Supervisor: Li-na Wang<br><br><br>E-mail: wangrun[at]whu.edu.cn<br>Office: Room C309, Computer  School, Wuhan University, Hubei Province"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true
