# general configuration
url: http://miwong.me
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/profile.jpg"
  # author will appear under the avatar (optional)
  author: "Michelle Wong"
  # tagline will appear under the title (optional)
  tagline: "PhD student in computer security"
  about: "Dept. of Electrical and Computer Engineering<br>University of Toronto<br><br>Supervisor: David Lie<br><br><br>E-mail: michelley.wong[at]mail.utoronto.ca<br>Office: D.L. Pratt Building, Room 372"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true
